import { environment } from '../../environments/environment';

export const Constantes = {
   CONST_ENDPOINT_PROXY: environment.url_proxy,//NECESARIA PARA PRIMER CARGUE PROPIEDADES
   CONST_ENDPOINT_SER_GENERAL: environment.url_sergeneral,//NECESARIA PARA REGISTRO LOGS
   ENDPOINT_LIGA_CAMPEONES: environment.url_ligaCampeones,
   ENDPOINT_SUCCESS_FACTOR: 'app.liga.endpoint.success',   
   ENDPOINT_OBTENER_IP: 'app.endpoint.obtener.ip',
   CONST_REDENCION_X_RECARGA: "1",
   CONST_REDENCION_X_TERMINAL: "2",
   CONST_REFERIR: 1,
   CONST_TIPO_CONTRATO_ALIADO_SUCCESS_FACTOR: "Aliado",
   CONST_TIPO_CONTRATO_INDEFINIDO_SUCCESS_FACTOR: "Indefinido",
   CONST_TIPO_CONTRATO_TERCERO: "TERCEROS",
   CONST_TIPO_CONTRATO_DIRECTO: "DIRECTO",
   CONST_CATEGORIA_ACTIVA: 1,
   CONST_TIMEOUT_GENERAL: "app.liga.timeout.general",
   CONST_TIMEOUT_INACTIVIDAD: "app.liga.timeout.inactividad",
   TIEMPO_EXPIRACION: 'app.liga.tiempo.expiracion.pagina',
   CANTIDAD_MINIMA_ARTICULOS: 'app.liga.cantidad.minima.articulos',
   BANNER_IMG: 'app.liga.banner.img',
   CANTIDAD_IMG: 'app.liga.cantidad.img',
   INICIO_IMG: 'app.liga.img.inicio',
   ESTADO_POLITICAS_VIGENTES: 'app.liga.estado.politicas.vigentes',
   TITULO_POLITICAS_VIGENTES: 'app.liga.titulo.politicas.vigentes',
   POLITICAS_VIGENTES: 'app.liga.politicas.vigentes',
   MIN_LENGTH_PSW: 'app.liga.tamano.min.pass',
   MAX_LENGTH_PSW: 'app.liga.tamano.max.pass',
   TAMANO_PAGINA: 'app.liga.cant.reg.x.pagina',
   MAX_SIZE_IMAGE: 'app.liga.max.size.imgSrc',
   MSG_MAX_SIZE_IMAGE_LIMIT: 'app.liga.msg.max.size.img',
   PROP_USUARIO_ACTIVO: 0,
   PROP_USUARIO_INACTIVO: 1,
   NOMBRE_ARCHIVO_DESC_ACT_PEDIDOS: 'app.liga.nombre.arc.descarga.act.pedido',
   TEXTO_CONTACTENOS: 'app.liga.texto.contactenos',
   CORREO_CONTACTENOS: 'app.liga.correo.contactenos',
   PRODUCTOS_REFERIDOS: 'app.liga.producto.referido',
   SEGMENTO_REFERIDOS: 'app.liga.segmento.referido',
   URL_GET_COMPROBATE_STATE: 'app.liga.url.GetComprobateStateTransfer',
   COMPROBATE_STATE_CABECERA_LOGIN: 'app.liga.comprobateState.cabecera.login',
   COMPROBATE_STATE_CABECERA_PASSWORD: 'app.liga.comprobateState.cabecera.password',
   COMPROBATE_STATE_CABECERA_CODE: 'app.liga.comprobateState.cabecera.GatewayCode',
   COMPROBATE_STATE_CABECERA_TYPE: 'app.liga.comprobateState.cabecera.GatewayType',
   COMPROBATE_STATE_CABECERA_PORT: 'app.liga.comprobateState.cabecera.servicePort',
   COMPROBATE_STATE_CABECERA_SOURSETYPE: 'app.liga.comprobateState.cabecera.sourceType',
   COMPROBATE_STATE_TYPE: 'app.liga.comprobateState.type',
   COMPROBATE_STATE_EXTNWCODE: 'app.liga.comprobateState.extNwCode',
   COMPROBATE_STATE_CATCODE: 'app.liga.comprobateState.catCode',
   COMPROBATE_STATE_EMPCODE: 'app.liga.comprobateState.empCode',
   COMPROBATE_STATE_LOGINID: 'app.liga.comprobateState.loginId',
   COMPROBATE_STATE_PASSWORD: 'app.liga.comprobateState.password',
   COMPROBATE_STATE_EXTREFNUM: 'app.liga.comprobateState.extRefNum',   
   COMPROBATE_STATE_DATA_TRFCATEGORY: 'app.liga.comprobateState.data.trfCategory',
   COMPROBATE_STATE_DATA_FROMDATE: 'app.liga.comprobateState.data.fromDate',
   COMPROBATE_STATE_DATA_TODATE: 'app.liga.comprobateState.data.toDate',
   
   URL_UPDATE_OPERATION_TRANSFER: 'app.liga.url.UpdateOperationTransfer',
   UPDATE_OPERATION_CABECERA_LOGIN: 'app.liga.updateOper.cabecera.login',
   UPDATE_OPERATION_CABECERA_PASSWORD: 'app.liga.updateOper.cabecera.password',
   UPDATE_OPERATION_CABECERA_CODE: 'app.liga.updateOper.cabecera.requestGatewayCode',
   UPDATE_OPERATION_CABECERA_TYPE: 'app.liga.updateOper.cabecera.requestGatewayType',
   UPDATE_OPERATION_CABECERA_PORT: 'app.liga.updateOper.cabecera.servicePort',
   UPDATE_OPERATION_CABECERA_SOURSETYPE: 'app.liga.updateOper.cabecera.sourceType',   
   UPDATE_OPERATION_TYPE: 'app.liga.updateOper.type',
   UPDATE_OPERATION_EXTNWCODE: 'app.liga.updateOper.extNwCode',
   UPDATE_OPERATION_PIN: 'app.liga.updateOper.pin',
   UPDATE_OPERATION_EXTCODE: 'app.liga.updateOper.extCode',
   UPDATE_OPERATION_PRODUCTS_PRODUCTCODE: 'app.liga.updateOper.products.productCode',   
   UPDATE_OPERATION_TRFCATEGORY: 'app.liga.updateOper.trfCategory',
   UPDATE_OPERATION_REFNUMBER: 'app.liga.updateOper.refNumber',
   UPDATE_OPERATION_PAYMENTDETAILS_PAYMENTTYPE: 'app.liga.updateOper.paymentDet.paymentType',
   UPDATE_OPERATION_PAYMENTDETAILS_PAYMENTINSTNUMBER: 'app.liga.updateOper.paymentDet.paymentInstNumber',  
   UPDATE_OPERATION_REMARKS: 'app.liga.updateOper.remarks',

   MSG_EXITOSO_RECARGA: 'app.liga.msg.exitoso.recarga',
   MSG_ERROR_RECARGA: 'app.liga.msg.error.recarga',
   MSG_ERROR_INTERNO_RECARGA: 'app.liga.msg.errorInterno.recarga',
   TRUE: "true",
   ADMIN: "admin",
   PROP_PERFIL_LOGUEADO: "PROP_PERFIL_LOGUEADO",
   PROP_TIPO_CONTRATO_LOGIN: "PROP_TIPO_CONTRATO_LOGIN",
   COOKIE_ID_CONTRATO_REGISTRAR: "COOKIE_ID_CONTRATO_REGISTRAR",
   COOKIE_ID_PERFIL_REGISTRAR: "COOKIE_ID_PERFIL_REGISTRAR",
   COOKIE_NOMBRE_PERFIL_REGISTRAR: "COOKIE_NOMBRE_PERFIL_REGISTRAR",
   PROP_ID_PERFIL_ADMIN: "1",
   PROP_ID_PERFIL_VENDEDOR: 2,
   PROP_ID_PERFIL_DIRECTO: 3,
   PROP_ID_PERFIL_TECNICO: 4,
   // PROP_ID_PERFIL_VENDEDOR: "app.liga.perfil.idVendedor",
   NOMBRE_USUARIO: "nombre_usuario",
   CEDULA: "cedula",
   CANALES: "canales",
   USUARIO: "usuario",
   CODIGO_EXITOSO: 0,
   CODIGO_EXITOSO_HTTP: 200,
   CODIGO_ERROR: -6,
   ID_IMG_GENERAL: 'assets/img/Imagen',
   MIN_LENGTH: 10,
   PATRON_DIGITOS: /^[3]{1}\d{9}/,
   PATRON_SOLO_DIGITOS: /^([0-9])*$/,
   PATRON_CORREO: /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,3}$/,
   PATRON_PSW: /^(?!.*(?:123|abc|ABC|Abc|aBc|abC|ABc|aBC|AbC)).*$/,
   MAX_LENGTH_CEL: 10,
   TIPO_ARCHIVO_EXCEL: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=UTF-8',
   SEPARADOR: '|',
   HTTP_STATUS_CODE_500: 500,
   HTTP_STATUS_MSJ_500: 'Error Interno',
   HTTP_STATUS_CODE_CONTENIDO_PARCIAL: 206,
   CANAL_APLICACION: 'WEB',
   UUID: 'UUID',
   NOMBRE_APLICACION: 'LIGA_CAMPEONES_WEB',
   NOMBRE_APLICACION_BANNER: 'LIGA_CAMPEONES_WEB_BANNER',
   IMAGEN_X_DEFECTO: './assets/img/lapiz.png',
   CONST_RUTA_URL_LOGS: '/logs/guardar',
   CONST_ACCION_CONSULTAR: "c",
   CONST_ACCION_INSERTAR: "i",
   CONST_ACCION_ACTUALIZAR: "a",
   CONST_ACCION_ELIMINAR: "e",
   CONST_LISTADO_ESTADOS: "Activo,Inactivo",
   TERMINOS_Y_CONDICIONES_REFERIDOS: 'app.liga.tipo.contrato_5',
   TIPO_REDENCION: "MANUAL,RECARGA,TERMINAL",
   TIPO_VISUALIZACION_PREGUNTA: "Login,Usuario,Completa",
   PROP_ENDPOINT_CHAMPIONS_LEAGUE: "app.endpoint.champions.league",
   PROP_RUTA_CL_START_ORDER: "app.ruta.champions.league.start.order",
   CONST_STATUS_CODE_OK: "200",
   CONST_ESTADO_PRODUCTO_RECHAZADO: 10,
   CONST_ESTADO_PRODUCTO_APROBADO: 90,
   CONST_ENVIO_CORREO_CUENTA: 32,
   PARAMETRO_CORREO_ACTUALIZACION_CUENTA: 'app.liga.parametros.correo.actualizacion.cuenta',
   SECCION_IMG: 'Preguntas',
   PARAMETRIZACION_MODULOS: 'Editar Información,Editar Términos y Condiciones,Editar Mensajes,Editar Segmentos,Preguntas Frecuentes',
   PROP_COMPONENTE_FLOTANTE_NAME: "app.componente.flotante.nombre",
   PROP_COMPONENTE_FLOTANTE_URL: "app.componente.flotante.url",
   PROP_COMPONENTE_ESTADO: "app.componente.estado",
   PROP_INACT_USUARIO: "app.inactivacion.usuario",
   PROP_ACTIVACION_VENCIMIENTO:"app.vencimiento.puntos.inhabilitacion",
   PROP_TIPO_CONTRATO: 'app.liga.tipo.contrato',
   PROP_ERROR_CONSULTA_SUCCESS_FACTOR: 'app.mensaje.consulta.success.factor',
   PROP_CONTRATOS: 'app.liga.array.terminos',
   PROP_VENCIMIENTO_PQRS:'app.liga.vencimiento.pqrs',
   PROP_CANTIDAD_RESPUESTAS_PQRS:'app.liga.cant.respuestas.pqrs',
   PROP_ASUNTO_USUARIO_PQRS:'app.liga.asunto.usuario.pqrs',
   PROP_CUERPO_USUARIO_PQRS:'app.liga.cuerpo.usuario.pqrs',   
   PROP_DESTINATARIOS_USUARIO_PQRS:'app.liga.destinatario.usuario.pqrs',
   PROP_CORREOS_PQRS:'app.liga.correos.pqrs',
   CONST_TIPO_REPORTE_PQR_RESUMIDO : 'R',
   CONST_ESTADO_PQR_RECIBIDA : 'RECIBIDA',
   CONST_ESTADO_PQR_CERRADA : 'CERRADA',
   CONST_ESTADO_PQR_EN_REVISION : 'EN REVISION',
   CONST_ESTADO_PQR_ATENDIDA : 'ATENDIDA',
   CONST_REGISTRO_NUEVO: 'nuevo',
   CONST_INICIAR_SESION: 'Iniciar sesión',
   CONST_REGISTRATE_GANA: '¡Regístrate y GANA!',
   CONST_USUARIO_PASS: 'Ingresa digitando tu usuario y contraseña',
   CONST_INGRESA_PASS: 'Debe ingresar su contraseña',
   CONST_INGRESA_PERFIL: 'Debe seleccionar perfil',
   CONST_OLVIDE_PASS: 'Olvidé mi contraseña',
   CONST_NO_REGISTRADO: '¿Aún no estás registrado?',
   CONST_INICA_REGISTRO: 'Comienza el registro digitando tu cédula',
   CONST_REGISTRAME: 'Régistrarme',
   CONS_CONTACTO: 'Contacto ',
   CONS_PARTICIPA_CONCURSO: 'app.liga.nombre.concurso',
   CONS_DESC_CONCUR_PARTE_UNO: 'app.liga.descripcion.concurso.uno',
   CONS_DESC_CONCUR_PARTE_DOS: 'app.liga.descripcion.concurso.dos',
   CONS_NOMBRE_CONCURSO: 'app.liga.nombre.concurso.negrita',
  
   
   
   CONST_ACTIVO : 1,
   PROP_PQR_LINES_USER_FTP         : "app.pqr.user.ftp",
   PROP_PQR_LINES_HOST_FTP         : "app.pqr.host.ftp",
   PROP_PQR_LINES_PASS_FTP         : "app.pqr.pass.ftp",
   PROP_PQR_LINES_PATH_FTP         : "app.pqr.path.ftp",
   CONST_PQR_CERRADA_PETICION_USUARIO : 'CERRADA',
   PROP_PQR_CONFIGURACION_MSJ : "app.liga.pqr.configuracion.msjs",
   PROP_MSJ_CREAR_PQR : "prop.crear.pqr",
   PROP_MSJ_PQR_CREADA : "prop.pqr.creada",
   PROP_MSJ_AVISO_CERRAR_PQR : "prop.aviso.cerrar.pqr",
   PROP_MSJ_PQR_RESPONDIDA : "prop.pqr.respondida",
   PROP_MSJ_PQR_CERRADA : "prop.pqr.cerrada",
   PROP_MSJ_CONFIRMAR_RTA_PQR : "prop.confirmar.respuesta.pqr",
   PROP_MSJ_ULTIMA_OBJECION : "prop.msj.ultima.objecion",
   PROP_MSJ_CANT_RTAS_PQR : "prop.cantidad.respuestas.pqr",
   PROP_MSJ_CANT_DIAS_HAB_PQR : "prop.cantidad.dias.habiles.pqr",
   PROP_PQR_TIPO_SOLICITUD : "app.liga.pqr.tipo.solicitud",
   PROP_PQR_ACTIVACION:"prop.pqr.activacion",
   PROP_PQR_CANTIDAD_ADJUNTOS_PERMITIDOS:"prop.pqr.cantidad.adjuntos",
   PROP_PQR_MAXIMO_PESO_ADJUNTOS:"prop.pqr.maximo.peso.adjuntos"
}